### ISSUE TITLE
Make instructions clearer

### ISSUE THREAD

**Issue by kenticomartinh** [makma/gatsby-starter-kontent-lumen#6]
### Motivation

Instructions need some polishing in order to make it dummy-proof

### Proposed solution

https://github.com/makma/gatsby-starter-kontent-lumen#import-sample-data-and-content-structure-from-the-source-project-into-your-project-using-kontent-backup-manager-codecli

Avoid **X or Y** instructions - The setup is already quite complex, choose what's the easiest path. If there is a separate path for console preferring users and UI preferring users, create two separate tutorials ...

When one forgets to prepare languages, the backup manager fails, and upon re-run fails with error message that folders already exist. There should be extra instruction that a cleanup is needed for retry. Also consider parameter `importLanguages` to avoid the language preparation step

Step 3 is there multiple times

**Comment by makma** [comment]
Hi @kenticomartinh, thank you for creating the issue and pushing the auto-language-creating feature in the CLI repo. I've adjusted import instructions according to your feedback.

Thank you 🎉
